version: '3'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
  rocket:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: rockettalk
    volumes:
      - .:/app
    ports:
      - "8000:8000"